
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv export zsh)"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

eval $(dircolors)

ZVM_INIT_MODE=sourcing
ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_ZLE

setopt autocd
setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

fpath=(/usr/share/zsh/site-functions $fpath)

export EDITOR="nvim"
export PATH="${PATH}:/home/paul/.cargo/bin"
export PATH="${PATH}:/home/paul/.config/emacs/bin"
export PATH="${PATH}:/home/paul/.local/bin"
export PATH="${PATH}:/opt/platform-tools"
export PATH="${PATH}:/opt/gnirehtet-rust-linux64"
export PATH="${PATH}:/opt/pdfsizeopt"
export PATH="${PATH}:/opt/verapdf"
export PATH="${PATH}:/opt/nvim-linux64/bin"
export PATH="/usr/local/texlive/2022/bin/x86_64-linux:${PATH}"
export PATH="/opt/emacs-29.1/src/:${PATH}"
export MANPATH="${MANPATH}:/usr/local/texlive/2022/texmf-dist/doc/man"
export INFOPATH="${INFOPATH}:/usr/local/texlive/2022/texmf-dist/doc/info"
export LSP_USE_PLISTS=true

alias ls="exa"
alias l="exa -lag"
alias 2up="sudo apt update && sudo apt upgrade"
alias open="xdg-open"
alias zshrc="nvim ~/.zshrc && source ~/.zshrc"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# https://unix.stackexchange.com/a/97844
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

if [ -n "${INSIDE_EMACS+1}" ]
then
    bindkey "$terminfo[kcuu1]" history-beginning-search-backward-end
    bindkey "$terminfo[kcud1]" history-beginning-search-forward-end
else
    bindkey -v
    zvm_after_init_commands+=("bindkey '^k' history-beginning-search-backward-end" "bindkey '^j' history-beginning-search-forward-end")
    source ~/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
    export FZF_DEFAULT_OPTS='--color 16'
fi

source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.fzf-tab/fzf-tab.plugin.zsh
source ~/.powerlevel10k/powerlevel10k.zsh-theme
source "$HOME/.cargo/env"

# Customize FZF
_fzf_compgen_path() {
  fdfind --hidden --exclude ".git" --follow . "$1"
}

_fzf_compgen_dir() {
  fdfind --type=d --hidden --exclude ".git" --follow . "$1"
}

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
# update new installed programs
zstyle ':completion:*' rehash true
# accept with tab
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# opam configuration
[[ ! -r /home/paul/.opam/opam-init/init.zsh ]] || source /home/paul/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
